language: R
r: 4.1.3
sudo: false
cache: packages

# define system dependencies that your R package needs
addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - r-base-dev
      - libmagick++-dev
      - libharfbuzz-dev
      - libfreetype6-dev
      - libfribidi-dev

# run tests
script:
  - R CMD build .
  - R CMD check *tar.gz

# specify the different versions of R to test against
matrix:
  include:
    - r: oldrel
    - r: release
    - r: devel
