language: shell

services:
  - docker

before_install:
  - docker pull rocker/r-ver:4.1.3

# run tests
script:
  - docker run -d -p 127.0.0.1:8989:8787 rocker/r-ver:4.1.3 /bin/sh -c "apt-get update && apt-get install -y libmagick++-dev libharfbuzz-dev libfreetype6-dev libfribidi-dev && cd /usr; R CMD check *tar.gz"
