language: R
cache: packages

services:
  - docker

before_install:
  - docker pull rocker/r-base:4.1.3
  - docker run -d -p 127.0.0.1:8888:8787 rocker/r-base:4.1.3 /bin/sh -c "cd /usr; R CMD build ."
  - docker ps -a

# define system dependencies that your R package needs
addons:
  apt:
    packages:
      - libmagick++-dev
      - libharfbuzz-dev
      - libfreetype6-dev
      - libfribidi-dev

# run tests
script:
  - docker run -d -p 127.0.0.1:8989:8787 rocker/r-base:4.1.3 /bin/sh -c "cd /usr; R CMD check *tar.gz"
