services:
  - docker

before_install:
  - docker pull rocker/r-base:4.1.3
  - docker run -d -p 127.0.0.1:80:8787 rocker/r-base:4.1.3 /bin/sh -c "cd /usr; R CMD build ."
  - docker ps -a

# define system dependencies that your R package needs
addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - r-base-dev
      - libmagick++-dev
      - libharfbuzz-dev
      - libfreetype6-dev
      - libfribidi-dev

# run tests
script:
  - docker run -d -p 127.0.0.1:80:8787 rocker/r-base:4.1.3 /bin/sh -c "cd /usr; R CMD check *tar.gz"
