language: R
sudo: false
cache: packages

# specify the R version
r:
  - 4.1.3

# define system dependencies that your R package needs
addons:
  apt:
    packages:
      - libmagick++-dev

# run tests
script:
  - R CMD build .
  - R CMD check *tar.gz

# specify the different versions of R to test against
matrix:
  include:
    - r: oldrel
    - r: release
    - r: devel
